### ISSUE TITLE
Namespaces ignore other namespaces without defined parents

### ISSUE THREAD

**Issue by yjr4df0708** [tgrysztar/fasmg#18]
This code:
```
namespace A
    B=0
end namespace

namespace C
    D=A.B
end namespace
```
results in an error because it cannot find "A.B" in C's namespace:
```
flat assembler  version g.kd3c
bug.asm [6]:
        D=A.B
Processed: D=A.B
Error: symbol 'C.A.B' is undefined or out of scope.
```

Adding any definition to A in global scope, like inserting `A=0` outside of the namespaces allows `C.D` to find `A.B`.

**Comment by bitRAKE** [comment]
One of the challenging things with `fasmg` is that many things which are commonly a combined operation are many separate syntactical mechanisms. With regard to namespaces the defining of symbols is separate than their searchability from the global scope. To make the `A` namespace searchable use `define A`.
```
define A
namespace A
    B=0
end namespace

namespace C
    D=A.B
end namespace
```
Also, it can be confusing because:
```
namespace A
    B=0
end namespace
E=A.B
```
... works, but the cross-namespace access is not automatic.

It can be quite challenging, but this verbosity makes the language nuanced and flexible.

**Comment by yjr4df0708** [comment]
I found this behavior and found it linked to whether `A` had a dummy definition, and thought it could only be unintended, as I couldn't think of a reason for this, I didn't see it mentioned in the manual, and it seemed logical how behavior like this could happen unintentionally.

I'll close this issue as it is apparently intended.
